version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "3000:3000"
    env_file:
      - ./backend/server.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - onboarding-net

  employee-frontend:
    build: ./frontend
    container_name: employee-frontend
    ports:
      - "8001:80"
    networks:
      - onboarding-net

  hr-frontend:
    build: ./hr-page
    container_name: hr-frontend
    ports:
      - "8002:80"
    networks:
      - onboarding-net

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: onboarding
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - onboarding-net

volumes:
  postgres-data:

networks:
  onboarding-net:

